version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/easysell
  SPRING_DATASOURCE_USERNAME: app
  SPRING_DATASOURCE_PASSWORD: app2022

services:
  db:
    container_name: postgres
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_cliente:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: easysell
      POSTGRES_PASSWORD: app2022
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5455:5432"
    mem_limit: 300m

  app:
    image: registry.hub.docker.com/pedrofff/springboot:latest
    container_name: Spring

    ports:
      - "8080:8080"
    mem_limit: 500m
    environment:
      <<: *database-variables

    depends_on:
      - db

volumes:
  base_cliente:
    external: true

