#server:
#  error:
#    include-stacktrace: on_param
#
#spring:
#  application:
#    name: springboot
#  datasource:
#    url: jdbc:postgresql://localhost:5455/easysell
#    username: app
#    password: app2022
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#    hibernate:
#      ddl-auto: update
#
#  thymeleaf:
#    mode: html

#  spring.thymeleaf.mode= html
#  spring.jpa.hibernate.ddl-auto=update
#
#  spring.datasource.url=jdbc:postgresql://localhost:5455/easysell
#  spring.datasource.username=app
#  spring.datasource.password=app2022
#  spring.jpa.database=postgresql
#
#  spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true